### ISSUE TITLE
Travis failing when we run tests

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WebApp#1732]
### Please describe the issue (What happens? What do you expect?)
- [ ] There is a versioning problem with enzyme and chai that prevents our tests from running (since our upgrade to node 10.10+, React 16 and Bootstrap 4)
- [ ] We also need to programmatically provide a /WebApp/src/js/config.js file

![fireshot capture 023 - build 2661 - wevote__ - https___travis-ci org_wevote_webapp_builds_443481081](https://user-images.githubusercontent.com/7756031/47192763-d1061700-d303-11e8-9880-698bab426e17.png)

$ git clone --depth=50 https://github.com/wevote/WebApp.git wevote/WebApp
Cloning into 'wevote/WebApp'...
remote: Enumerating objects: 2524, done.
remote: Counting objects: 100% (2524/2524), done.
remote: Compressing objects: 100% (1243/1243), done.
remote: Total 2524 (delta 1439), reused 1948 (delta 1264), pack-reused 0
Receiving objects: 100% (2524/2524), 3.85 MiB | 18.88 MiB/s, done.
Resolving deltas: 100% (1439/1439), done.
$ cd wevote/WebApp
$ git fetch origin +refs/pull/1735/merge:
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 39 (delta 33), reused 33 (delta 28), pack-reused 0
Unpacking objects: 100% (39/39), done.
From https://github.com/wevote/WebApp
 * branch            refs/pull/1735/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
Setting environment variables from .travis.yml
$ export SAUCE_USERNAME=WeVote
$ export SAUCE_ACCESS_KEY=eb6e0454-e844-4a1a-a695-2d5830897566
nvm.setup
$ export PATH=./node_modules/.bin:$PATH
Updating nvm
nvm.install
2.44s$ nvm install 10.12.0
Downloading and installing node v10.12.0...
Downloading https://nodejs.org/dist/v10.12.0/node-v10.12.0-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v10.12.0 (npm v6.4.1)
$ node --version
v10.12.0
$ npm --version
6.4.1
$ nvm --version
0.33.11
JWT addon will be deprecated on April 17, 2018. Please read our announcement at https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated
install.npm
32.27s$ npm ci 
> node-sass@4.9.4 install /home/travis/build/wevote/WebApp/node_modules/node-sass
> node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-64_binding.node
Download complete
Binary saved to /home/travis/build/wevote/WebApp/node_modules/node-sass/vendor/linux-x64-64/binding.node
Caching binary to /home/travis/.npm/node-sass/4.9.4/linux-x64-64_binding.node
> node-sass@4.9.4 postinstall /home/travis/build/wevote/WebApp/node_modules/node-sass
> node scripts/build.js
Binary found at /home/travis/build/wevote/WebApp/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine
> fsevents@1.2.3 install /home/travis/build/wevote/WebApp/node_modules/fsevents
> node install
> spawn-sync@1.0.15 postinstall /home/travis/build/wevote/WebApp/node_modules/spawn-sync
> node postinstall
> pre-commit@1.2.2 install /home/travis/build/wevote/WebApp/node_modules/pre-commit
> node install.js
added 2074 packages in 31.858s
before_script
5.02s$ npm install -g se-interpreter
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.1.14: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
/home/travis/.nvm/versions/node/v10.12.0/bin/se-interpreter -> /home/travis/.nvm/versions/node/v10.12.0/lib/node_modules/se-interpreter/interpreter.js
> deasync@0.1.13 install /home/travis/.nvm/versions/node/v10.12.0/lib/node_modules/se-interpreter/node_modules/deasync
> node ./build.js
`linux-x64-node-10` exists; testing
Binary is fine; exiting
> wd@1.11.0 install /home/travis/.nvm/versions/node/v10.12.0/lib/node_modules/se-interpreter/node_modules/wd
> node scripts/build-browser-scripts
+ se-interpreter@1.0.10
added 119 packages from 113 contributors in 4.562s
1.14s$ npm run autoTest
> wevoteusa@1.0.0 autoTest /home/travis/build/wevote/WebApp
>  mocha --compilers js:babel-core/register --require tests/component/index.js "./tests/component/tests.js" && npm run lint
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
internal/modules/cjs/loader.js:582
    throw err;
    ^
Error: Cannot find module 'react-dom/lib/ReactTestUtils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/travis/build/wevote/WebApp/node_modules/react-addons-test-utils/index.js:73:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/wevote/WebApp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/travis/build/wevote/WebApp/node_modules/chai-jsx/node_modules/react-element-to-jsx-string/index-dist.js:18:29)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/wevote/WebApp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/travis/build/wevote/WebApp/node_modules/chai-jsx/chai-jsx.js:1:31)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/wevote/WebApp/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/travis/build/wevote/WebApp/tests/component/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at loader (/home/travis/build/wevote/WebApp/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/wevote/WebApp/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requires.forEach.mod (/home/travis/build/wevote/WebApp/node_modules/mocha/bin/_mocha:511:3)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/travis/build/wevote/WebApp/node_modules/mocha/bin/_mocha:510:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wevoteusa@1.0.0 autoTest: ` mocha --compilers js:babel-core/register --require tests/component/index.js "./tests/component/tests.js" && npm run lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wevoteusa@1.0.0 autoTest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-10-19T01_25_58_778Z-debug.log
The command "npm run autoTest" exited with 1.
31.76s$ se-interpreter tests/selenium/interpreter_config.json
SE-Interpreter 1.0.10
sample: Starting test (firefox) sample
sample: Success {"type":"get","url":"https://wevote.us/"}
sample: Test passed(firefox) 
sampleTest: Starting test (firefox) sampleTest
sampleTest: Success {"type":"get","url":"https://wevote.us/"}
sampleTest: Test passed(firefox) 
2/2 tests ran successfully. Exiting
The command "se-interpreter tests/selenium/interpreter_config.json" exited with 0.
Done. Your build exited with 1.

**Comment by gj262** [comment]
Hi @DaleMcGrew, I can take a look at this if no one has started on it yet,
Cheers,
-Gavin

**Comment by DaleMcGrew** [comment]
Hello @gj262, that would be excellent. Thank you! Do you know how I can give you the access you need to Travis to make any configuration changes that are needed?

**Comment by gj262** [comment]
Hi @DaleMcGrew, I have my own Travis setup so I _should_ be able to get it working in that. I'll holler if I need access to the wevote Travis. 
Cheers,
-Gavin

**Comment by gj262** [comment]
Passing Travis run here: https://travis-ci.org/gj262/WebApp/builds/444230087
